/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#fdd5e4",
        "on-secondary-fixed-variant": "#5b3f4b",
        "inverse-on-surface": "#f3f0f0",
        "error-container": "#ffdad6",
        "tertiary-container": "#624300",
        "secondary-fixed": "#ffd8e7",
        "on-tertiary": "#ffffff",
        "on-background": "#1b1c1c",
        "primary-fixed": "#ffd9e4",
        outline: "#857278",
        tertiary: "#452e00",
        "on-error-container": "#93000a",
        "surface-bright": "#fbf9f8",
        secondary: "#745663",
        "on-primary": "#ffffff",
        "surface-container": "#f0eded",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#d7c1c7",
        "on-error": "#ffffff",
        "on-tertiary-container": "#e0b05d",
        "on-secondary-container": "#795a67",
        "surface-variant": "#e4e2e1",
        primary: "#5e1739",
        "on-secondary": "#ffffff",
        "surface-dim": "#dcd9d9",
        error: "#ba1a1a",
        "on-primary-fixed": "#3e0021",
        "on-primary-container": "#fe9bc1",
        "on-surface-variant": "#534248",
        "tertiary-fixed": "#ffdeaa",
        "surface-container-highest": "#e4e2e1",
        "inverse-primary": "#ffb0cd",
        surface: "#fbf9f8",
        "surface-container-low": "#f5f3f2",
        "surface-tint": "#944366",
        "on-primary-fixed-variant": "#772c4e",
        "primary-fixed-dim": "#ffb0cd",
        "on-tertiary-fixed-variant": "#5f4100",
        "on-tertiary-fixed": "#271900",
        "inverse-surface": "#303030",
        "on-surface": "#1b1c1c",
        "primary-container": "#7a2e50",
        "tertiary-fixed-dim": "#f0bf69",
        background: "#fbf9f8",
        "on-secondary-fixed": "#2b141f",
        "secondary-fixed-dim": "#e3bccb",
        "surface-container-high": "#eae8e7",
        // Clinical status codes (from DESIGN.md, used as flat utilities e.g. bg-status-confirmada)
        "status-confirmada": "#2E7D5A",
        "status-confirmada-bg": "#EAF5F0",
        "status-pendiente": "#B57A22",
        "status-pendiente-bg": "#FCF6E8",
        "status-reprogramada": "#3E6B99",
        "status-reprogramada-bg": "#EDF4FA",
        "status-cancelada": "#9E4B5E",
        "status-cancelada-bg": "#F8EBEF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        "gutter-desktop": "1.5rem",
        gutter: "1rem",
        margin: "1rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "margin-desktop": "2.5rem",
        "space-xs": "0.25rem",
        "margin-tablet": "1.5rem",
      },
      fontFamily: {
        "title-sm": ["Montserrat"],
        "title-md": ["Montserrat"],
        "display-lg": ["Playfair Display"],
        "headline-sm": ["Montserrat"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Playfair Display"],
        "code-clinical": ["Inter"],
        "label-lg": ["Montserrat"],
        "headline-md": ["Playfair Display"],
        "headline-lg-mobile": ["Playfair Display"],
        "body-sm": ["Inter"],
        "label-md": ["Montserrat"],
        "headline-lg": ["Playfair Display"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "title-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "code-clinical": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
